[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov-branch --cov-report xml --cov-report term --cov=slurmmail -vv --strict-markers -rfE"
minversion = "6.0"
pythonpath = "src"
testpaths = [
    "tests/unit"
]

[tool.black]
preview-string-processing = true

[tool.coverage.run]
relative_files = true
