title: Slurm-Mail
email: neilmunday@users.noreply.github.com
description: >- 
  Provides customisable HTML5 e-mails for SLURM
baseurl: "/slurm-mail"
url: "https://neilmunday.github.io/slurm-mail"
github_username: neilmunday
show_downloads: true

# Build settings
remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
exclude:
  - tools/
  - doc/
