name: "Purge SLURM docker images"

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  purge_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: purge images
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tests/integration/docker-slurm/image-purge.sh
