name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        run: echo "VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: Create checkout directory
        run: mkdir slurm-mail-${VERSION}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: slurm-mail-${{env.VERSION}}
      - name: Build
        run: tar cvfz slurm-mail-${VERSION}.tar.gz --exclude .git* --exclude build slurm-mail-${VERSION}
      - name: Check tar
        run: tar tvfz slurm-mail-${VERSION}.tar.gz
      - name: Create tar md5sum
        run: md5sum slurm-mail-${VERSION}.tar.gz | awk '{ print $1 }' > slurm-mail-${VERSION}.tar.gz.md5sum
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            slurm-mail-${{env.VERSION}}.tar.gz
            slurm-mail-${{env.VERSION}}.tar.gz.md5sum
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
