name: release

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create tar
        id: create_tar
        run: >-
          echo "::set-output name=TAR_PATH::$(
            build/create-tar.sh
          )"
      - name: Get tar file name
        id: tar_name
        run: >-
          echo "::set-output name=TAR_NAME::$(
            basename ${{steps.create_tar.outputs.TAR_PATH}}
          )"
      - name: Move tar file
        run: mv -v ${{steps.create_tar.outputs.TAR_PATH}} ./
      - name: Create md5sum for tar file
        run: md5sum ${{steps.tar_name.outputs.TAR_NAME}} | awk '{ print $1}' > ${{steps.tar_name.outputs.TAR_NAME}}.md5sum
      - name: Cat md5sum
        run: cat ${{steps.tar_name.outputs.TAR_NAME}}.md5sum
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            ${{steps.tar_name.outputs.TAR_NAME}}
            ${{steps.tar_name.outputs.TAR_NAME}}.md5sum
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
