name: testing

on:
  pull_request:
    paths:
      - '.github/workflows/testing.yml'
      - 'setup.py'
      - 'slurmmail/*.py'
      - 'tests/*.py'
      - 'tests/run.sh'
      - 'tests/tests.yml'
  push:
    paths:
      - '.github/workflows/testing.yml'
      - 'setup.py'
      - 'slurmmail/*.py'
      - 'tests/*.py'
      - 'tests/run.sh'
      - 'tests/tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slurm-version: ["20.11.9", "21.08.8-2", "22.05.2"]
    steps:
      - uses: actions/checkout@v3
      - name: Run integration tests
        run: |
          tests/integration/run.sh -s "${{ matrix.slurm-version }}"
