name: testing

on:
  pull_request:
    paths:
      - 'bin/*.py'
      - 'tests/*.py'
      - 'tests/tests.yml'
  push:
    paths:
      - 'bin/*.py'
      - 'tests/*.py'
      - 'tests/tests.yml'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        slurm-version: ["20.11.9", "21.08.8-2", "22.05.0"]
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        run: |
          tests/run.sh -s "${{ matrix.slurm-version }}"
